import type { Locale } from "./content";

export type MenuItem = {
  name: string;
  price: string;
  star?: boolean;
};

export type MenuSection = {
  id: string;
  title: string;
  subtitle?: string;
  kicker: string;
  image: string;
  icon: "utensils" | "flame" | "soup" | "cake" | "fish" | "wine" | "sparkles";
  signature?: boolean;
  items: readonly MenuItem[];
  subsections?: readonly { title: string; items: readonly MenuItem[] }[];
};

/**
 * Menu transcribed verbatim from the printed carta in use at the venta.
 * "S/M" = según mercado (market price).
 */
export const MENU: Record<Locale, readonly MenuSection[]> = {
  es: [
    {
      id: "entrantes",
      title: "Entrantes",
      kicker: "01 · Para abrir",
      image: "carta6.jpg",
      icon: "utensils",
      items: [
        { name: "Habitas baby con huevos y jamón", price: "11,50" },
        { name: "Alcachofas braseadas con jamón y gambas", price: "12,00" },
        { name: "Queso curado de oveja", price: "13,50" },
        { name: "Queso de cabra", price: "11,50" },
        { name: "Salchichón ibérico", price: "11,00" },
        { name: "Setas con jamón y gambas", price: "11,00" },
        { name: "Jamón ibérico", price: "16,00" },
        { name: "Jamón serrano", price: "11,00" },
        { name: "Morcilla cruda o a la plancha", price: "10,00" },
        { name: "Chorizo en rama casero", price: "10,00" },
        { name: "Anchoas con tomate", price: "10,50" },
        { name: "Lomo de orza troceado en manteca", price: "10,00" },
        { name: "Revuelto de espárragos con gambas, jamón y huevo", price: "11,00" },
        { name: "Huevos rotos con jamón", price: "10,50" },
        { name: "Berenjenas", price: "9,00" },
        { name: "Pimientos fritos", price: "9,00" },
        { name: "Ración de embutido variado extra", price: "13,00" },
        { name: "Barca de embutidos ibéricos con tostas", price: "23,00" },
      ],
    },
    {
      id: "primeros",
      title: "Primeros Platos",
      kicker: "02 · De la olla",
      image: "carta4.jpg",
      icon: "soup",
      items: [
        { name: "Ensalada", price: "6,00" },
        { name: "Ensalada mixta", price: "6,00" },
        { name: "Ensaladilla cortijera", price: "7,00" },
        { name: "Gazpacho", price: "4,50" },
        { name: "Olla", price: "5,50" },
        { name: "Sopa de la Casa Castellana", price: "5,50" },
        { name: "Sopa de picadillo", price: "5,50" },
        { name: "Sopa de marisco", price: "6,00" },
        { name: "Sopa de espárragos", price: "5,50" },
        { name: "Setas al ajillo revueltas con patatas", price: "10,50" },
        { name: "Porra fría", price: "6,50" },
        { name: "Porra caliente de setas y patatas", price: "8,00" },
        { name: "Gazpachuelo", price: "6,00" },
        { name: "Arroz", price: "7,50" },
        { name: "Migas con chorizo y melón", price: "9,00" },
        { name: "Migas completas (huevo, pimiento, chorizo y morcilla)", price: "14,90" },
      ],
    },
    {
      id: "pescados",
      title: "Pescados",
      kicker: "03 · Del mar",
      image: "carta2.jpg",
      icon: "fish",
      items: [
        { name: "Lubina a la espalda salteada con verduras", price: "14,90" },
        { name: "Pulpo a la brasa especial salteado con verduras y patatas", price: "21,50" },
        { name: "Calamares", price: "10,00" },
        { name: "Rosada", price: "11,00" },
        { name: "Calamaritos", price: "10,00" },
        { name: "Jibia", price: "11,00" },
        { name: "Almejas", price: "10,00" },
        { name: "Bacalao con tomate", price: "12,00" },
        { name: "Bacalao frito", price: "9,90" },
        { name: "Bacalao a la Vizcaína", price: "10,00" },
        { name: "Gambas rebozadas", price: "9,90" },
        { name: "Gambas a la plancha", price: "15,00" },
        { name: "Gambas cocidas", price: "15,00" },
        { name: "Gambas al pil-pil", price: "12,00" },
        { name: "Pez espada a la plancha", price: "12,50" },
        { name: "Fritura de pescado", price: "11,00" },
        { name: "Revuelto de verano", price: "9,50" },
        { name: "Pulpo a la Gallega", price: "19,50" },
        { name: "Rejos de calamar fritos o plancha", price: "19,50" },
        { name: "Calamar plancha extra (entero)", price: "19,50" },
        { name: "Variados de pescado a la plancha", price: "12,00" },
      ],
    },
    {
      id: "especialidades",
      title: "Especialidades de la Casa",
      subtitle: "Chivo, conejo y cordero a la brasa",
      kicker: "04 · Nuestra firma",
      image: "carta1.jpg",
      icon: "flame",
      signature: true,
      items: [
        { name: "Chivo al ajillo (ración)", price: "S/M", star: true },
        { name: "Chivo al ajillo con patatas", price: "S/M", star: true },
        { name: "Chuletillas de chivo al ajillo (ración)", price: "19,50", star: true },
        { name: "Chuletillas de chivo al ajillo con patatas", price: "19,50", star: true },
        { name: "Paletilla de chivo al horno", price: "23,00", star: true },
        { name: "Paletilla de chivo a la brasa", price: "19,90", star: true },
        { name: "Chuletillas de chivo empanadas", price: "15,90", star: true },
        { name: "Cordero troceado a la brasa (ración)", price: "19,50" },
        { name: "Cordero troceado a la brasa con patatas", price: "19,50" },
        { name: "Chuletillas de cordero a la brasa", price: "18,50" },
        { name: "Chuletillas de cordero con patatas", price: "19,50" },
        { name: "Chuletillas de cordero empanadas", price: "19,50" },
        { name: "Asadura de cordero", price: "9,50" },
        { name: "Conejo al ajillo", price: "9,00", star: true },
        { name: "Conejo a la brasa y patatas (medio)", price: "10,00", star: true },
        { name: "Entrecot de ternera (medio)", price: "20,00" },
        { name: "Chuletón de ternera", price: "20,00" },
        { name: "Jamón asado con patatas", price: "11,50" },
        { name: "Sangre de chivo encebollada", price: "10,00" },
      ],
    },
    {
      id: "carnes",
      title: "Carnes",
      kicker: "05 · A la brasa",
      image: "carta3.jpg",
      icon: "utensils",
      items: [
        { name: "San Jacobo con patatas fritas", price: "11,50" },
        { name: "Chuleta de cerdo con patatas", price: "9,90" },
        { name: "Chuleta de cerdo ibérica", price: "13,00" },
        { name: "Costilla de cerdo con patatas", price: "9,50" },
        { name: "Chorizo, huevo y patatas", price: "7,50" },
        { name: "Filete de lomo con patatas", price: "8,50" },
        { name: "Churrasco de cerdo a la brasa con patatas", price: "10,50" },
        { name: "Plato de los montes (chorizo, huevo, patatas, lomo y pimientos)", price: "14,90" },
        { name: "Carne en salsa", price: "9,50" },
        { name: "Carne al ajillo", price: "9,50" },
        { name: "Solomillo de cerdo con patatas", price: "12,50" },
        { name: "Filete de pollo a la plancha con patatas", price: "10,00" },
        { name: "Filete de pollo empanado con patatas", price: "10,00" },
        { name: "Pollo troceado a la brasa con patatas", price: "10,00" },
        { name: "Taco de lomo de orza con patatas", price: "10,00" },
        { name: "Filete de ternera", price: "10,00" },
        { name: "Filetillos de cerdo o pollo a la plancha", price: "9,90" },
        { name: "Filetillos de pollo o cerdo empanados", price: "9,90" },
        { name: "Croquetas", price: "9,50" },
        { name: "Flamenquín casero", price: "11,50" },
        { name: "Carrillada de cerdo extra con patatas", price: "13,90" },
        { name: "Solomillo de ternera", price: "25,00" },
        { name: "Secreto ibérico de bellota con patatas", price: "19,50" },
        { name: "Churrasco de pollo a la brasa con patatas", price: "10,50" },
        { name: "Manita de cerdo", price: "12,90" },
        { name: "Codillo de cerdo", price: "13,50" },
        { name: "Rabo de toro", price: "16,50" },
        { name: "Brocheta de solomillo o pollo acompañada con verduras y patatas", price: "11,50" },
        { name: "Lagarto ibérico de bellota con patatas", price: "17,50" },
      ],
    },
    {
      id: "vinos",
      title: "Vinos",
      kicker: "06 · Bodega",
      image: "bg2.jpg",
      icon: "wine",
      items: [],
      subsections: [
        {
          title: "Riojas",
          items: [
            { name: "Marqués de Cáceres 3/4", price: "17,00" },
            { name: "Marqués de Cáceres 3/8", price: "12,00" },
            { name: "Marqués de Riscal 3/4", price: "26,00" },
            { name: "Campillos Crianza 3/4", price: "24,50" },
            { name: "Coto Crianza 3/4", price: "14,50" },
            { name: "Apilizcueta", price: "16,00" },
            { name: "Vivanco", price: "17,50" },
            { name: "Progelio Crianza", price: "19,50" },
            { name: "Biga Luberri", price: "17,50" },
            { name: "Ramón Bilbao", price: "18,00" },
          ],
        },
        {
          title: "Ribera del Duero",
          items: [
            { name: "Senderillo de la casa", price: "15,00" },
            { name: "Marqués de Murrieta Reserva", price: "35,00" },
            { name: "Portia Roble", price: "16,00" },
            { name: "Portia Crianza", price: "20,00" },
            { name: "Melior", price: "16,50" },
            { name: "Prados del Rey", price: "16,50" },
            { name: "Protos", price: "17,00" },
            { name: "Erial de Bodegas Pesquera", price: "20,50" },
            { name: "Vizcarra", price: "20,50" },
            { name: "Quinta de Tarsus", price: "18,00" },
            { name: "Matarromera", price: "30,50" },
            { name: "Pago de Carroviejas", price: "28,00" },
            { name: "Pago de Capellanes Roble", price: "28,00" },
            { name: "Pago de Capellanes Crianza", price: "37,00" },
            { name: "Pesquera", price: "28,50" },
            { name: "Emilio Moro", price: "29,50" },
            { name: "Resalso", price: "19,00" },
          ],
        },
        {
          title: "Vinos de la Tierra de Castilla",
          items: [
            { name: "Yllera 3/4", price: "15,00" },
            { name: "Yllera 3/8", price: "10,50" },
            { name: 'Manzanilla "La Guita"', price: "14,00" },
            { name: "Barbadillo", price: "11,00" },
            { name: "Viña Tendida", price: "11,00" },
            { name: "Abadía del Roble", price: "10,50" },
            { name: "Jarrón de vino de los montes", price: "11,00" },
            { name: "Medio jarrón de vino de los montes", price: "7,00" },
            { name: "Botella tinto con casera o limón", price: "9,50" },
          ],
        },
      ],
    },
    {
      id: "postres",
      title: "Postres",
      kicker: "07 · Para terminar",
      image: "carta5.jpg",
      icon: "cake",
      items: [
        { name: "Leche frita", price: "4,50" },
        { name: "Bienmesabe", price: "4,50" },
        { name: "Flan casero", price: "4,50" },
        { name: "Natillas caseras", price: "4,00" },
        { name: "Arroz con leche casero", price: "4,00" },
        { name: "Piña", price: "4,00" },
        { name: "Melocotón", price: "4,00" },
        { name: "Tocino de cielo", price: "4,00" },
        { name: "Crema catalana", price: "4,50" },
        { name: "Mousse de chocolate", price: "4,50" },
        { name: "Crema de yogurt con tocino de cielo", price: "4,50" },
        { name: "Requesones caseros", price: "4,50" },
        { name: "Tarta de queso", price: "4,50" },
        { name: "Tarta al whisky", price: "4,50" },
        { name: "Tarta de manzana", price: "4,50" },
        { name: "Comtessa", price: "5,00" },
        { name: "Helados", price: "S/M" },
        { name: "Tarta de chocolate", price: "4,50" },
        { name: "Tarta milhoja", price: "4,50" },
        { name: "Tarta turrón", price: "6,00" },
        { name: "Fruta de temporada", price: "S/M" },
      ],
    },
  ],
  en: [
    {
      id: "entrantes",
      title: "Starters",
      kicker: "01 · To begin",
      image: "carta6.jpg",
      icon: "utensils",
      items: [
        { name: "Baby broad beans with eggs and ham", price: "11,50" },
        { name: "Braised artichokes with ham and prawns", price: "12,00" },
        { name: "Aged sheep's cheese", price: "13,50" },
        { name: "Goat's cheese", price: "11,50" },
        { name: "Iberian salchichón", price: "11,00" },
        { name: "Wild mushrooms with ham and prawns", price: "11,00" },
        { name: "Iberian ham", price: "16,00" },
        { name: "Serrano ham", price: "11,00" },
        { name: "Morcilla, raw or grilled", price: "10,00" },
        { name: "House-made chorizo", price: "10,00" },
        { name: "Anchovies with tomato", price: "10,50" },
        { name: "Cured pork loin in lard (lomo de orza)", price: "10,00" },
        { name: "Scrambled eggs with asparagus, prawns and ham", price: "11,00" },
        { name: "Broken eggs with Iberian ham", price: "10,50" },
        { name: "Aubergines", price: "9,00" },
        { name: "Fried peppers", price: "9,00" },
        { name: "Extra charcuterie platter", price: "13,00" },
        { name: "Iberian charcuterie board with toasts", price: "23,00" },
      ],
    },
    {
      id: "primeros",
      title: "First Courses",
      kicker: "02 · From the pot",
      image: "carta4.jpg",
      icon: "soup",
      items: [
        { name: "Green salad", price: "6,00" },
        { name: "Mixed salad", price: "6,00" },
        { name: "Country-style potato salad", price: "7,00" },
        { name: "Gazpacho", price: "4,50" },
        { name: "Olla (Andalusian stew)", price: "5,50" },
        { name: "Castilian house soup", price: "5,50" },
        { name: "Sopa de picadillo (broth with ham and egg)", price: "5,50" },
        { name: "Seafood soup", price: "6,00" },
        { name: "Asparagus soup", price: "5,50" },
        { name: "Garlic mushrooms scrambled with potatoes", price: "10,50" },
        { name: "Cold porra", price: "6,50" },
        { name: "Hot porra with mushrooms and potatoes", price: "8,00" },
        { name: "Gazpachuelo", price: "6,00" },
        { name: "Rice", price: "7,50" },
        { name: "Migas with chorizo and melon", price: "9,00" },
        { name: "Full migas (egg, pepper, chorizo and morcilla)", price: "14,90" },
      ],
    },
    {
      id: "pescados",
      title: "Fish",
      kicker: "03 · From the sea",
      image: "carta2.jpg",
      icon: "fish",
      items: [
        { name: "Sea bass sautéed with vegetables", price: "14,90" },
        { name: "Special grilled octopus with vegetables and potatoes", price: "21,50" },
        { name: "Squid", price: "10,00" },
        { name: "Rosada", price: "11,00" },
        { name: "Baby squid", price: "10,00" },
        { name: "Cuttlefish", price: "11,00" },
        { name: "Clams", price: "10,00" },
        { name: "Cod with tomato", price: "12,00" },
        { name: "Fried cod", price: "9,90" },
        { name: "Cod Biscay-style", price: "10,00" },
        { name: "Battered prawns", price: "9,90" },
        { name: "Grilled prawns", price: "15,00" },
        { name: "Boiled prawns", price: "15,00" },
        { name: "Prawns pil-pil", price: "12,00" },
        { name: "Grilled swordfish", price: "12,50" },
        { name: "Fish fry", price: "11,00" },
        { name: "Summer scramble", price: "9,50" },
        { name: "Galician-style octopus", price: "19,50" },
        { name: "Squid legs, fried or grilled", price: "19,50" },
        { name: "Whole grilled squid (large)", price: "19,50" },
        { name: "Mixed grilled fish plate", price: "12,00" },
      ],
    },
    {
      id: "especialidades",
      title: "House Specialities",
      subtitle: "Goat, rabbit and lamb, from the grill",
      kicker: "04 · Our signature",
      image: "carta1.jpg",
      icon: "flame",
      signature: true,
      items: [
        { name: "Garlic goat (portion)", price: "market", star: true },
        { name: "Garlic goat with potatoes", price: "market", star: true },
        { name: "Garlic goat chops (portion)", price: "19,50", star: true },
        { name: "Garlic goat chops with potatoes", price: "19,50", star: true },
        { name: "Roast goat shoulder", price: "23,00", star: true },
        { name: "Grilled goat shoulder", price: "19,90", star: true },
        { name: "Breaded goat chops", price: "15,90", star: true },
        { name: "Grilled lamb pieces (portion)", price: "19,50" },
        { name: "Grilled lamb pieces with potatoes", price: "19,50" },
        { name: "Grilled lamb chops", price: "18,50" },
        { name: "Lamb chops with potatoes", price: "19,50" },
        { name: "Breaded lamb chops", price: "19,50" },
        { name: "Lamb offal", price: "9,50" },
        { name: "Garlic rabbit", price: "9,00", star: true },
        { name: "Half grilled rabbit with potatoes", price: "10,00", star: true },
        { name: "Half beef entrecôte", price: "20,00" },
        { name: "Veal T-bone steak", price: "20,00" },
        { name: "Roast ham with potatoes", price: "11,50" },
        { name: "Goat blood with onion", price: "10,00" },
      ],
    },
    {
      id: "carnes",
      title: "Meats",
      kicker: "05 · From the grill",
      image: "carta3.jpg",
      icon: "utensils",
      items: [
        { name: "San Jacobo with fries", price: "11,50" },
        { name: "Pork chop with potatoes", price: "9,90" },
        { name: "Iberian pork chop", price: "13,00" },
        { name: "Pork ribs with potatoes", price: "9,50" },
        { name: "Chorizo, egg and potatoes", price: "7,50" },
        { name: "Pork loin fillet with potatoes", price: "8,50" },
        { name: "Grilled pork churrasco with potatoes", price: "10,50" },
        { name: "Plato de los montes (chorizo, egg, potatoes, loin and peppers)", price: "14,90" },
        { name: "Meat in sauce", price: "9,50" },
        { name: "Garlic meat", price: "9,50" },
        { name: "Pork tenderloin with potatoes", price: "12,50" },
        { name: "Grilled chicken fillet with potatoes", price: "10,00" },
        { name: "Breaded chicken fillet with potatoes", price: "10,00" },
        { name: "Grilled chicken pieces with potatoes", price: "10,00" },
        { name: "Lomo de orza taco with potatoes", price: "10,00" },
        { name: "Beef fillet", price: "10,00" },
        { name: "Grilled pork or chicken strips", price: "9,90" },
        { name: "Breaded pork or chicken strips", price: "9,90" },
        { name: "Croquettes", price: "9,50" },
        { name: "House flamenquín", price: "11,50" },
        { name: "Extra braised pork cheeks with potatoes", price: "13,90" },
        { name: "Beef tenderloin", price: "25,00" },
        { name: "Acorn-fed Iberian secreto with potatoes", price: "19,50" },
        { name: "Grilled chicken churrasco with potatoes", price: "10,50" },
        { name: "Pig trotter", price: "12,90" },
        { name: "Pork knuckle", price: "13,50" },
        { name: "Oxtail", price: "16,50" },
        { name: "Sirloin or chicken skewer with vegetables and potatoes", price: "11,50" },
        { name: "Acorn-fed Iberian lagarto with potatoes", price: "17,50" },
      ],
    },
    {
      id: "vinos",
      title: "Wines",
      kicker: "06 · Cellar",
      image: "bg2.jpg",
      icon: "wine",
      items: [],
      subsections: [
        {
          title: "Rioja",
          items: [
            { name: "Marqués de Cáceres 3/4", price: "17,00" },
            { name: "Marqués de Cáceres 3/8", price: "12,00" },
            { name: "Marqués de Riscal 3/4", price: "26,00" },
            { name: "Campillos Crianza 3/4", price: "24,50" },
            { name: "Coto Crianza 3/4", price: "14,50" },
            { name: "Apilizcueta", price: "16,00" },
            { name: "Vivanco", price: "17,50" },
            { name: "Progelio Crianza", price: "19,50" },
            { name: "Biga Luberri", price: "17,50" },
            { name: "Ramón Bilbao", price: "18,00" },
          ],
        },
        {
          title: "Ribera del Duero",
          items: [
            { name: "House selection (Senderillo)", price: "15,00" },
            { name: "Marqués de Murrieta Reserva", price: "35,00" },
            { name: "Portia Roble", price: "16,00" },
            { name: "Portia Crianza", price: "20,00" },
            { name: "Melior", price: "16,50" },
            { name: "Prados del Rey", price: "16,50" },
            { name: "Protos", price: "17,00" },
            { name: "Erial de Bodegas Pesquera", price: "20,50" },
            { name: "Vizcarra", price: "20,50" },
            { name: "Quinta de Tarsus", price: "18,00" },
            { name: "Matarromera", price: "30,50" },
            { name: "Pago de Carroviejas", price: "28,00" },
            { name: "Pago de Capellanes Roble", price: "28,00" },
            { name: "Pago de Capellanes Crianza", price: "37,00" },
            { name: "Pesquera", price: "28,50" },
            { name: "Emilio Moro", price: "29,50" },
            { name: "Resalso", price: "19,00" },
          ],
        },
        {
          title: "Vinos de la Tierra de Castilla",
          items: [
            { name: "Yllera 3/4", price: "15,00" },
            { name: "Yllera 3/8", price: "10,50" },
            { name: 'Manzanilla "La Guita"', price: "14,00" },
            { name: "Barbadillo", price: "11,00" },
            { name: "Viña Tendida", price: "11,00" },
            { name: "Abadía del Roble", price: "10,50" },
            { name: "Jug of house wine", price: "11,00" },
            { name: "Half jug of house wine", price: "7,00" },
            { name: "House bottle with soda or lemon", price: "9,50" },
          ],
        },
      ],
    },
    {
      id: "postres",
      title: "Desserts",
      kicker: "07 · To finish",
      image: "carta5.jpg",
      icon: "cake",
      items: [
        { name: "Fried milk", price: "4,50" },
        { name: "Bienmesabe", price: "4,50" },
        { name: "House flan", price: "4,50" },
        { name: "House custard", price: "4,00" },
        { name: "House rice pudding", price: "4,00" },
        { name: "Pineapple", price: "4,00" },
        { name: "Peach", price: "4,00" },
        { name: "Tocino de cielo", price: "4,00" },
        { name: "Crema catalana", price: "4,50" },
        { name: "Chocolate mousse", price: "4,50" },
        { name: "Yoghurt cream with tocino de cielo", price: "4,50" },
        { name: "House-made curd cheeses", price: "4,50" },
        { name: "Cheesecake", price: "4,50" },
        { name: "Whisky tart", price: "4,50" },
        { name: "Apple tart", price: "4,50" },
        { name: "Comtessa", price: "5,00" },
        { name: "Ice cream", price: "market" },
        { name: "Chocolate tart", price: "4,50" },
        { name: "Mille-feuille tart", price: "4,50" },
        { name: "Turrón tart", price: "6,00" },
        { name: "Seasonal fruit", price: "market" },
      ],
    },
  ],
} as const;
