import type { Locale } from "./content";

export type MenuItem = {
  name: string;
  price: string;
  star?: boolean;
};

export type MenuSection = {
  id: string;
  title: string;
  subtitle?: string;
  kicker: string;
  image: string;
  icon: "utensils" | "flame" | "soup" | "cake" | "fish" | "wine" | "sparkles";
  signature?: boolean;
  items: readonly MenuItem[];
  subsections?: readonly { title: string; items: readonly MenuItem[] }[];
};

/**
 * Menu transcribed from the current printed carta (designed 2026).
 * "S/M" = según mercado (market price).
 */
export const MENU: Record<Locale, readonly MenuSection[]> = {
  es: [
    {
      id: "entrantes",
      title: "Entrantes",
      kicker: "01 · Para abrir",
      image: "carta6.jpg",
      icon: "utensils",
      items: [
        { name: "Habitas baby con huevos y jamón", price: "11,50" },
        { name: "Alcachofas braseadas con jamón", price: "9,90" },
        { name: "Queso curado de oveja con membrillo", price: "13,90" },
        { name: "Queso de cabra", price: "9,50" },
        { name: "Salchichón ibérico", price: "9,50" },
        { name: "Chorizo ibérico", price: "9,50" },
        { name: "Selección ibéricos y gambas", price: "12,00" },
        { name: "Jamón ibérico", price: "11,50" },
        { name: "Jamón serrano o a la plancha", price: "8,50" },
        { name: "Chorizo en rama casero", price: "9,50" },
        { name: "Anchoas con tomate", price: "11,00" },
        { name: "Lomo de orza de la casa", price: "11,00" },
        { name: "Pimientos fritos", price: "9,00" },
        { name: "Ración de embutidos ibéricos con tostas", price: "23,00" },
      ],
    },
    {
      id: "primeros",
      title: "Primeros Platos",
      kicker: "02 · De la olla",
      image: "carta4.jpg",
      icon: "soup",
      items: [
        { name: "Ensalada mixta", price: "6,00" },
        { name: "Ensalada aventera", price: "7,00" },
        { name: "Gazpacho", price: "6,00" },
        { name: "Sopa de la casa castellana", price: "5,50" },
        { name: "Sopa de picadillo", price: "5,50" },
        { name: "Sopa de marisco", price: "7,50" },
        { name: "Sopa de la Casa Cortijuelo", price: "5,50" },
        { name: "Porra fría", price: "6,00" },
        { name: "Gazpachuelo", price: "6,50" },
        { name: "Arroz", price: "7,00" },
        { name: "Migas con chorizo y melón", price: "9,00" },
        { name: "Migas con huevo frito", price: "9,50" },
        { name: "Setas al ajillo revueltas con patatas", price: "10,50" },
        { name: "Revuelto de setas y patatas", price: "10,50" },
      ],
    },
    {
      id: "pescados",
      title: "Pescados",
      kicker: "03 · Del mar",
      image: "carta2.jpg",
      icon: "fish",
      items: [
        { name: "Lubina a la espalda salteada con verduras y patatas", price: "21,50" },
        { name: "Pulpo a la brasa salteado con verduras y patatas", price: "14,90" },
        { name: "Gambas al ajillo especial del Cortijuelo con verduras y patatas", price: "15,00" },
        { name: "Calamaritos", price: "10,00" },
        { name: "Jibia", price: "10,00" },
        { name: "Gambas al pil-pil", price: "11,00" },
        { name: "Gambas a la plancha", price: "15,00" },
        { name: "Bacalao frito", price: "12,00" },
        { name: "Bacalao a la vizcaína", price: "12,00" },
        { name: "Almejas", price: "9,90" },
        { name: "Boquerones", price: "9,90" },
        { name: "Rosada", price: "10,00" },
      ],
    },
    {
      id: "especialidades",
      title: "Especialidades de la Casa",
      subtitle: "Chivo, conejo y cordero a la brasa",
      kicker: "04 · Nuestra firma",
      image: "carta1.jpg",
      icon: "flame",
      signature: true,
      items: [
        { name: "Chivo al ajillo", price: "15,00", star: true },
        { name: "Chivo frito", price: "15,00", star: true },
        { name: "Chivo al ajillo con patatas", price: "16,00", star: true },
        { name: "Chivo frito con patatas", price: "17,00", star: true },
        { name: "Chuletillas de chivo al ajillo", price: "19,00", star: true },
        { name: "Chuletillas de chivo a la brasa", price: "19,00", star: true },
        { name: "Paletilla de chivo a la brasa", price: "23,00", star: true },
        { name: "Chivo lechal", price: "S/M", star: true },
        { name: "Chuletillas de cordero lechal a la brasa", price: "23,00" },
        { name: "Cordero troceado a la brasa (con patatas)", price: "19,00" },
        { name: "Chuletillas de cordero empanadas con patatas", price: "19,50" },
        { name: "Conejo al ajillo", price: "9,50", star: true },
        { name: "Conejo al ajillo con patatas", price: "10,50", star: true },
        { name: "Chuletillas de conejo empanadas con patatas", price: "10,50", star: true },
        { name: "Conejo a la brasa", price: "9,50", star: true },
        { name: "Chuletillas de conejo a la brasa", price: "10,50", star: true },
        { name: "Entrécot de ternera con patatas (medio)", price: "20,00" },
        { name: "Chuletillas de ternera con patatas", price: "20,00" },
        { name: "Sangre de chivo encebollada", price: "10,00" },
      ],
    },
    {
      id: "carnes",
      title: "Carnes",
      kicker: "05 · A la brasa",
      image: "carta3.jpg",
      icon: "utensils",
      items: [
        { name: "San Jacobo con patatas fritas", price: "11,50" },
        { name: "Chuleta de cerdo con patatas", price: "9,00" },
        { name: "Chuleta de cerdo ibérica", price: "13,90" },
        { name: "Costilla de cerdo con patatas", price: "9,90" },
        { name: "Chuletón de buey con patatas", price: "16,50" },
        { name: "Entrecot de ternera con patatas", price: "19,50" },
        { name: "Solomillo de cerdo con patatas", price: "12,50" },
        { name: "Filete de pollo a la plancha con patatas", price: "10,00" },
        { name: "Filete de pollo empanado con patatas", price: "10,00" },
        { name: "Pollo troceado a la brasa con patatas", price: "10,00" },
        { name: "Rabo de toro", price: "13,50" },
        { name: "Brocheta de solomillo o pollo con patatas", price: "11,50" },
        { name: "Lagarto ibérico de bellota con patatas", price: "17,50" },
      ],
    },
    {
      id: "vinos",
      title: "Vinos",
      kicker: "06 · Bodega",
      image: "bg2.jpg",
      icon: "wine",
      items: [],
      subsections: [
        {
          title: "Riojas",
          items: [
            { name: "Marqués de Cáceres 3/4", price: "17,00" },
            { name: "Marqués de Cáceres 3/8", price: "12,00" },
            { name: "Marqués de Riscal 3/4", price: "26,00" },
            { name: "Marqués de Riscal 3/8", price: "17,00" },
            { name: "Coto Crianza 3/4", price: "17,00" },
            { name: "Coto Crianza 3/8", price: "12,00" },
            { name: "Aplicazueta", price: "14,50" },
            { name: "Progelio Crianza", price: "17,50" },
            { name: "Biga Luberri", price: "17,50" },
            { name: "Ramón Bilbao", price: "18,00" },
          ],
        },
        {
          title: "Ribera del Duero",
          items: [
            { name: "Senderillo de la casa", price: "15,00" },
            { name: "Marqués de Valparíeta Reserva", price: "16,00" },
            { name: "Portia Roble", price: "15,00" },
            { name: "Pago de Carroviejas", price: "28,00" },
            { name: "Pago de Capellanes Roble", price: "37,00" },
            { name: "Pago de Capellanes Crianza", price: "28,00" },
            { name: "Pesquera Crianza", price: "30,50" },
            { name: "Emilio Moro", price: "29,50" },
            { name: "Resalso", price: "19,00" },
          ],
        },
        {
          title: "Vinos de la Tierra de Castilla",
          items: [
            { name: "Yllera 3/4", price: "15,00" },
            { name: "Yllera 3/8", price: "10,50" },
            { name: 'Tierra de Castilla "La Guita"', price: "14,00" },
            { name: "Marqués de Riscal 3/4", price: "11,00" },
            { name: "Barbadillo", price: "11,00" },
            { name: "Viña Tendria", price: "10,00" },
            { name: "Abadía del Roble", price: "10,00" },
            { name: "Jarrón de vino de los montes", price: "9,00" },
            { name: "Copa de vino de los montes", price: "7,50" },
            { name: "Medio jarrón de vino de los montes", price: "5,00" },
            { name: "Botella tinto con casera o limón", price: "9,50" },
          ],
        },
      ],
    },
    {
      id: "postres",
      title: "Postres",
      kicker: "07 · Para terminar",
      image: "carta5.jpg",
      icon: "cake",
      items: [
        { name: "Leche frita", price: "4,50" },
        { name: "Bienmesabe", price: "4,50" },
        { name: "Flan casero", price: "4,00" },
        { name: "Natillas caseras", price: "4,00" },
        { name: "Arroz con leche casero", price: "4,00" },
        { name: "Tocino de cielo", price: "4,00" },
        { name: "Crema catalana", price: "4,50" },
        { name: "Mousse de chocolate", price: "4,50" },
        { name: "Tarta de queso casera", price: "4,50" },
        { name: "Tarta de manzana", price: "4,50" },
        { name: "Tarta al whisky", price: "6,00" },
        { name: "Tarta de chocolate", price: "4,50" },
        { name: "Tarta milhojas", price: "4,50" },
        { name: "Tarta de turrón", price: "4,50" },
        { name: "Fruta de temporada", price: "S/M" },
        { name: "Helados", price: "5,00" },
      ],
    },
  ],
  en: [
    {
      id: "entrantes",
      title: "Starters",
      kicker: "01 · To begin",
      image: "carta6.jpg",
      icon: "utensils",
      items: [
        { name: "Baby broad beans with eggs and ham", price: "11,50" },
        { name: "Braised artichokes with ham", price: "9,90" },
        { name: "Aged sheep's cheese with quince", price: "13,90" },
        { name: "Goat's cheese", price: "9,50" },
        { name: "Iberian salchichón", price: "9,50" },
        { name: "Iberian chorizo", price: "9,50" },
        { name: "Iberian charcuterie & prawns", price: "12,00" },
        { name: "Iberian ham", price: "11,50" },
        { name: "Serrano ham, sliced or grilled", price: "8,50" },
        { name: "House-made chorizo", price: "9,50" },
        { name: "Anchovies with tomato", price: "11,00" },
        { name: "House lomo de orza", price: "11,00" },
        { name: "Fried peppers", price: "9,00" },
        { name: "Iberian charcuterie board with toasts", price: "23,00" },
      ],
    },
    {
      id: "primeros",
      title: "First Courses",
      kicker: "02 · From the pot",
      image: "carta4.jpg",
      icon: "soup",
      items: [
        { name: "Mixed salad", price: "6,00" },
        { name: "Winnower's salad (aventera)", price: "7,00" },
        { name: "Gazpacho", price: "6,00" },
        { name: "Castilian house soup", price: "5,50" },
        { name: "Sopa de picadillo (broth with ham and egg)", price: "5,50" },
        { name: "Seafood soup", price: "7,50" },
        { name: "Casa Cortijuelo soup", price: "5,50" },
        { name: "Cold porra", price: "6,00" },
        { name: "Gazpachuelo", price: "6,50" },
        { name: "Rice", price: "7,00" },
        { name: "Migas with chorizo and melon", price: "9,00" },
        { name: "Migas with fried egg", price: "9,50" },
        { name: "Garlic mushrooms scrambled with potatoes", price: "10,50" },
        { name: "Scrambled mushrooms and potatoes", price: "10,50" },
      ],
    },
    {
      id: "pescados",
      title: "Fish",
      kicker: "03 · From the sea",
      image: "carta2.jpg",
      icon: "fish",
      items: [
        { name: "Sea bass sautéed with vegetables and potatoes", price: "21,50" },
        { name: "Grilled octopus with vegetables and potatoes", price: "14,90" },
        { name: "Special Cortijuelo garlic prawns with vegetables and potatoes", price: "15,00" },
        { name: "Baby squid", price: "10,00" },
        { name: "Cuttlefish", price: "10,00" },
        { name: "Prawns pil-pil", price: "11,00" },
        { name: "Grilled prawns", price: "15,00" },
        { name: "Fried cod", price: "12,00" },
        { name: "Cod Biscay-style", price: "12,00" },
        { name: "Clams", price: "9,90" },
        { name: "Anchovies", price: "9,90" },
        { name: "Rosada", price: "10,00" },
      ],
    },
    {
      id: "especialidades",
      title: "House Specialities",
      subtitle: "Goat, rabbit and lamb, from the grill",
      kicker: "04 · Our signature",
      image: "carta1.jpg",
      icon: "flame",
      signature: true,
      items: [
        { name: "Garlic goat", price: "15,00", star: true },
        { name: "Fried goat", price: "15,00", star: true },
        { name: "Garlic goat with potatoes", price: "16,00", star: true },
        { name: "Fried goat with potatoes", price: "17,00", star: true },
        { name: "Garlic goat chops", price: "19,00", star: true },
        { name: "Grilled goat chops", price: "19,00", star: true },
        { name: "Grilled goat shoulder", price: "23,00", star: true },
        { name: "Milk-fed goat", price: "market", star: true },
        { name: "Grilled milk-fed lamb chops", price: "23,00" },
        { name: "Grilled lamb pieces with potatoes", price: "19,00" },
        { name: "Breaded lamb chops with potatoes", price: "19,50" },
        { name: "Garlic rabbit", price: "9,50", star: true },
        { name: "Garlic rabbit with potatoes", price: "10,50", star: true },
        { name: "Breaded rabbit chops with potatoes", price: "10,50", star: true },
        { name: "Grilled rabbit", price: "9,50", star: true },
        { name: "Grilled rabbit chops", price: "10,50", star: true },
        { name: "Half beef entrecôte with potatoes", price: "20,00" },
        { name: "Veal chops with potatoes", price: "20,00" },
        { name: "Goat blood with onion", price: "10,00" },
      ],
    },
    {
      id: "carnes",
      title: "Meats",
      kicker: "05 · From the grill",
      image: "carta3.jpg",
      icon: "utensils",
      items: [
        { name: "San Jacobo with fries", price: "11,50" },
        { name: "Pork chop with potatoes", price: "9,00" },
        { name: "Iberian pork chop", price: "13,90" },
        { name: "Pork ribs with potatoes", price: "9,90" },
        { name: "Ox T-bone with potatoes", price: "16,50" },
        { name: "Beef entrecôte with potatoes", price: "19,50" },
        { name: "Pork tenderloin with potatoes", price: "12,50" },
        { name: "Grilled chicken fillet with potatoes", price: "10,00" },
        { name: "Breaded chicken fillet with potatoes", price: "10,00" },
        { name: "Grilled chicken pieces with potatoes", price: "10,00" },
        { name: "Oxtail", price: "13,50" },
        { name: "Sirloin or chicken skewer with potatoes", price: "11,50" },
        { name: "Acorn-fed Iberian lagarto with potatoes", price: "17,50" },
      ],
    },
    {
      id: "vinos",
      title: "Wines",
      kicker: "06 · Cellar",
      image: "bg2.jpg",
      icon: "wine",
      items: [],
      subsections: [
        {
          title: "Rioja",
          items: [
            { name: "Marqués de Cáceres 3/4", price: "17,00" },
            { name: "Marqués de Cáceres 3/8", price: "12,00" },
            { name: "Marqués de Riscal 3/4", price: "26,00" },
            { name: "Marqués de Riscal 3/8", price: "17,00" },
            { name: "Coto Crianza 3/4", price: "17,00" },
            { name: "Coto Crianza 3/8", price: "12,00" },
            { name: "Aplicazueta", price: "14,50" },
            { name: "Progelio Crianza", price: "17,50" },
            { name: "Biga Luberri", price: "17,50" },
            { name: "Ramón Bilbao", price: "18,00" },
          ],
        },
        {
          title: "Ribera del Duero",
          items: [
            { name: "House selection (Senderillo)", price: "15,00" },
            { name: "Marqués de Valparíeta Reserva", price: "16,00" },
            { name: "Portia Roble", price: "15,00" },
            { name: "Pago de Carroviejas", price: "28,00" },
            { name: "Pago de Capellanes Roble", price: "37,00" },
            { name: "Pago de Capellanes Crianza", price: "28,00" },
            { name: "Pesquera Crianza", price: "30,50" },
            { name: "Emilio Moro", price: "29,50" },
            { name: "Resalso", price: "19,00" },
          ],
        },
        {
          title: "Vinos de la Tierra de Castilla",
          items: [
            { name: "Yllera 3/4", price: "15,00" },
            { name: "Yllera 3/8", price: "10,50" },
            { name: 'Tierra de Castilla "La Guita"', price: "14,00" },
            { name: "Marqués de Riscal 3/4", price: "11,00" },
            { name: "Barbadillo", price: "11,00" },
            { name: "Viña Tendria", price: "10,00" },
            { name: "Abadía del Roble", price: "10,00" },
            { name: "Jug of house wine", price: "9,00" },
            { name: "Glass of house wine", price: "7,50" },
            { name: "Half jug of house wine", price: "5,00" },
            { name: "House bottle with soda or lemon", price: "9,50" },
          ],
        },
      ],
    },
    {
      id: "postres",
      title: "Desserts",
      kicker: "07 · To finish",
      image: "carta5.jpg",
      icon: "cake",
      items: [
        { name: "Fried milk", price: "4,50" },
        { name: "Bienmesabe", price: "4,50" },
        { name: "House flan", price: "4,00" },
        { name: "House custard", price: "4,00" },
        { name: "House rice pudding", price: "4,00" },
        { name: "Tocino de cielo", price: "4,00" },
        { name: "Crema catalana", price: "4,50" },
        { name: "Chocolate mousse", price: "4,50" },
        { name: "House-made cheesecake", price: "4,50" },
        { name: "Apple tart", price: "4,50" },
        { name: "Whisky tart", price: "6,00" },
        { name: "Chocolate tart", price: "4,50" },
        { name: "Mille-feuille tart", price: "4,50" },
        { name: "Turrón tart", price: "4,50" },
        { name: "Seasonal fruit", price: "market" },
        { name: "Ice cream", price: "5,00" },
      ],
    },
  ],
} as const;
